### ISSUE TITLE
[Bug] VoxCPM2 instruct ignored in VoiceStudio 0.5.2

### ISSUE THREAD

**Issue by nevilbutani** [debpalash/VoiceStudio#2093]
<html><body>
<html><head></head><body><p>[Bug] VoxCPM2 instruct/style controls are ignored in VoiceStudio 0.5.2</p><h2>1. What happened?</h2><p>VoxCPM2 voice cloning works correctly in VoiceStudio 0.5.2, but its style/emotion/instruction controls appear to be ignored.</p><p>The important part is that <strong>the underlying VoxCPM2 model itself supports style control correctly</strong>. I tested the same voice reference directly with VoxCPM2 2.0.3, and changing the native parenthetical instruction produced clearly different delivery. However, the same style instructions do not work through VoiceStudio.</p><h3>Environment</h3>

- VoiceStudio: 0.5.2
- Windows
- GPU: RTX 5070 Ti 16 GB
- Python: 3.11.15
- PyTorch: 2.8.0+cu128
- VoxCPM: 2.0.3
- Engine: VoxCPM2
- Voice: NehaS (`3c26ca80`)

<p>The VoiceStudio health endpoint also reports:</p><pre><code class="language-json">{
  "status": "ok",
  "device": "cuda (NVIDIA GeForce RTX 5070 Ti)",
  "version": "0.5.2"
}</code></pre></body></html>
</body>
</html>

<hr><h2>2. Steps to reproduce</h2><h3>A. Test through the Voice Clone UI</h3><ol><li><p>Open VoiceStudio 0.5.2.</p></li><li><p>Go to <strong>Voice Clone → From audio</strong>.</p></li><li><p>Select the saved voice <strong>NehaS</strong>.</p></li><li><p>Select <strong>VoxCPM2</strong> as the engine.</p></li><li><p>Leave the Style field empty.</p></li><li><p>Enter the following text:</p></li></ol><pre><code class="language-text">(screaming at the top of your lungs, extremely angry, furious, shouting) NO! GET AWAY FROM ME RIGHT NOW! DON'T YOU EVER COME BACK!</code></pre><ol start="7"><li><p>Generate the audio.</p></li></ol><h3>Actual result</h3><p>The parenthetical instruction is spoken literally as part of the audio instead of being interpreted as a style/emotion instruction.</p><p>I also tested:</p><pre><code class="language-text">(whispering extremely quietly, terrified, trembling, almost crying) Please... don't leave me here alone. I'm scared.</code></pre><p>The instruction was again spoken literally instead of controlling the delivery.</p><hr><h3>B. Test through the VoiceStudio API</h3><p>VoiceStudio's <code>/openapi.json</code> exposes an <code>instruct</code> field in <code>SpeechRequest</code>, described as:</p><blockquote><p>Style instruction for the TTS engine.</p></blockquote><p>I tested:</p><pre><code class="language-json">{
  "model": "voxcpm2",
  "voice": "3c26ca80",
  "input": "THIS IS A VOXCPM2 EMOTION TEST! I can't believe this actually works!",
  "instruct": "speaking extremely fast and excited",
  "response_format": "wav"
}</code></pre><p>The request succeeds and generates audio, but the resulting speech remains essentially normal and the instruction does not produce the expected fast/excited delivery.</p><p>I also tested:</p><pre><code class="language-json">{
  "model": "voxcpm2",
  "voice": "3c26ca80",
  "input": "Please don't leave me here alone. I'm scared.",
  "instruct": "whispering extremely quietly, terrified, trembling, almost crying",
  "response_format": "wav"
}</code></pre><p>Again, the audio is generated successfully, but the instruction has no meaningful effect.</p><hr><h3>C. Direct VoxCPM2 comparison</h3><p>To make sure this was not a problem with the model, reference audio, GPU, or installation, I tested VoxCPM2 2.0.3 directly using the same voice reference:</p><pre><code class="language-text">C:\Users\Nevil\AppData\Roaming\OmniVoice\voices\3c26ca80.wav</code></pre><p>The direct VoxCPM2 test used the native VoxCPM2 style syntax:</p><pre><code class="language-python">wav = model.generate(
    text="(extremely slow, deeply sad, exhausted, almost crying) I don't want you to leave me.",
    reference_wav_path=r"C:\Users\Nevil\AppData\Roaming\OmniVoice\voices\3c26ca80.wav",
    cfg_value=2.0,
    inference_timesteps=10,
)</code></pre><p>and:</p><pre><code class="language-python">wav = model.generate(
    text="(extremely fast, furious, shouting, extremely angry) I don't want you to leave me!",
    reference_wav_path=r"C:\Users\Nevil\AppData\Roaming\OmniVoice\voices\3c26ca80.wav",
    cfg_value=2.0,
    inference_timesteps=10,
)</code></pre><p>These two direct VoxCPM2 generations produced <strong>clearly and dramatically different delivery</strong>.</p><p>This confirms that:</p><ul><li><p>The VoxCPM2 model supports the style control.</p></li><li><p>The reference voice works.</p></li><li><p>The VoxCPM2 installation works.</p></li><li><p>The GPU/backend works.</p></li><li><p>Parenthetical style instructions work when passed directly to VoxCPM2.</p></li></ul><p>The problem appears to be specifically in the VoiceStudio integration.</p><hr><h2>3. What did you expect instead?</h2><p>According to VoxCPM2's native behavior, text such as:</p><pre><code class="language-text">(extremely fast, furious, shouting) DON'T COME ANY CLOSER!</code></pre><p>should use the parenthetical portion as a style/emotion instruction rather than speaking it literally.</p><p>I would therefore expect VoiceStudio to correctly translate its <code>instruct</code> field into the VoxCPM2 native format:</p><pre><code class="language-text">(instruct)prompt</code></pre><p>For example:</p><pre><code class="language-text">(speaking extremely fast and excited) THIS IS A VOXCPM2 EMOTION TEST!</code></pre><p>The API's:</p><pre><code class="language-json">"instruct": "speaking extremely fast and excited"</code></pre><p>should have an equivalent effect.</p><h3>Expected vs actual</h3>
Test | Expected | Actual
-- | -- | --
UI parenthetical instruction | Controls emotion/style | Parenthetical is spoken literally
instruct via API | Changes delivery/style | Little or no noticeable effect
Direct VoxCPM2 (instruction)text | Changes delivery/style | Works correctly
Voice cloning | Preserves NehaS voice | Works correctly

<hr><h2>Possible cause</h2><p>It appears that VoiceStudio 0.5.2 may not be correctly forwarding or transforming the VoxCPM2 <code>instruct</code> value before calling the VoxCPM2 backend.</p><p>The relevant integration points may be:</p><ul><li><p><code>VoxCPM2Backend.generate</code></p></li><li><p><code>/v1/audio/speech</code> handling of <code>instruct</code></p></li><li><p>Voice Clone UI → VoxCPM2 request construction</p></li><li><p>Conversion of:</p></li></ul><pre><code class="language-text">instruct + prompt</code></pre><p>into the VoxCPM2-native:</p><pre><code class="language-text">(instruct)prompt</code></pre><p>There may also be a difference between the UI <code>/generate</code> path and the <code>/v1/audio/speech</code> path.</p><hr><h2>Additional information</h2><p>The VoiceStudio API reports version:</p><pre><code class="language-json">{
  "title": "VoiceStudio API",
  "version": "0.5.2"
}</code></pre><p>The installed managed Python environment is:</p><pre><code class="language-text">C:\Users\Nevil\AppData\Local\com.debpalash.omnivoice-studio\project\.venv</code></pre><p>VoxCPM is installed there as:</p><pre><code class="language-text">voxcpm-2.0.3</code></pre><p>Importing the package directly works:</p><pre><code class="language-python">import voxcpm
from voxcpm import VoxCPM</code></pre><p>So this does not appear to be a missing-package/import problem.</p><hr><h2>Summary</h2><p><strong>Voice cloning with VoxCPM2 works in VoiceStudio 0.5.2, but style/emotion/instruction control does not.</strong></p><p>The same VoxCPM2 model, same reference voice, and same machine produce strongly different emotional/expressive speech when called directly using the native VoxCPM2 <code>(instruction)text</code> syntax.</p><p>Because of that, this appears to be an issue with how VoiceStudio passes or handles VoxCPM2 style instructions rather than an issue with VoxCPM2 itself.</p><p>Could you please check whether the VoxCPM2 <code>instruct</code> value is actually being passed to the backend and converted to the required native <code>(instruct)prompt</code> format in VoiceStudio 0.5.2?</p><pre><code></code></pre></body></html>
</body>
</html>

**Comment by martinezpl** [comment]
Adding a second failure in the same adapter, found while I ran all 16 engines through a test script. Your report covers the **instruct** path (a reference clip plus a style string, spoken literally). The **voice design** path — a description with no reference clip — fails harder: it raises before any audio is made.

```
RuntimeError: voxcpm2 sidecar error: "TypeError: VoxCPM._generate() got an
unexpected keyword argument 'voice_description'"
```

Both code paths send that keyword:

- `backend/services/tts_backend.py:1166` (in-process)
- `backend/engines/voxcpm2_subprocess/main.py:191` (sidecar)

The pinned `voxcpm==2.0.3` has no such parameter, and no description-based API at all:

```
voxcpm 2.0.3
generate: (self, *args, **kwargs) -> numpy.ndarray
_generate: (self, text, prompt_wav_path=None, prompt_text=None, reference_wav_path=None,
            cfg_value=2.0, inference_timesteps=10, min_len=2, max_len=4096,
            normalize=False, denoise=False, retry_badcase=True, ...)
desc methods: []
```

`VoxCPM2Backend.supports_voice_design = True`, so the UI offers the control and every voice-design generation with this engine raises. The comment above the call still describes `generate_from_description()` as "the P0 feature from the roadmap"; that method does not exist in 2.0.3.

So both halves of the engine's style surface are broken against the pinned version — one silently, one with a `TypeError`. Probably one fix: reconcile the adapter with what `voxcpm==2.0.3` actually exposes, and drop `supports_voice_design` if the model has no equivalent.

For what it is worth, with no style controls at all VoxCPM2 was one of the best engines in the run — clean output in all three of English, Polish and Spanish.

Environment: VoiceStudio 0.5.2 (main @ `eaf8bb9`), macOS Apple M4 Pro, MPS, engine installed with the in-app one-click installer.

**Comment by debpalash** [comment]
The current sidecar already prefixes `(instruct)` to text, so the style problem needs a comparison of the UI, API and native calls rather than simply adding that prefix again. The reported design path also still passes `voice_description` and advertises design support. Reconcile both in-process and sidecar adapters with the pinned VoxCPM API, add routing/capability regressions, and preserve working reference cloning. Both failures remain in scope.
