### PR TITLE
fix: restore generation and startup broken by the rename

### PR DESCRIPTION
**Pull request by debpalash**
## What broke

Two bugs from the v0.4.2 rename sweep / migration chain, both found by running `main` end-to-end on Windows:

1. **Every default-engine generation fails** on anything built from `main` since 5cab8e01 — source checkouts, preview installers, and Docker `:latest` all run the same Python backend, whose lazy model import was rewritten to `from omnivoice.models.omnivoice import VoiceStudio`, a class the library doesn't export. `ImportError` isn't `ModuleNotFoundError`, so the #564 fallback doesn't catch it: `/generate` 500s with `cannot import name 'VoiceStudio'`.
2. **Startup dies when a DB migration is pending** in source/dev runs: alembic resolves the bare relative `script_location` against the process cwd, and the desktop shell launches the backend from `frontend/src-tauri`, so the first pending migration raised `MigrationError: Path doesn't exist: backend/migrations`. Latent until a migration actually pended.

## The fixes

- The model class keeps its library name (`OmniVoice` — a checkpoint-referenced identifier, not branding). The import site, docs, and Colab notebook revert to the exported API. A behavioral guard in the rename-guard suite pins `_lazy_omnivoice() is omnivoice.OmniVoice`.
- `alembic.ini` anchors `script_location` / `prepend_sys_path` with `%(here)s` and sets `path_separator = os` (legacy splitting shreds `C:\` paths and POSIX paths with spaces). The alembic floor rises to `>=1.16` (path_separator landed in 1.16.0, per CodeRabbit) (older versions silently ignore `path_separator`); `uv.lock` regenerated, pinned 1.18.4 unchanged.

## Verification

- Both regression tests verified fail-before/pass-after (including the `path_separator` half via an ini in a directory with a space).
- Live on Windows: app boots through a pending migration, then TTS, voice cloning, French synthesis, and an ASR round-trip (transcription matched the TTS input word-for-word) all pass; all 12 UI views mount clean.
- Full backend suite: no new failures beyond the ~25 known Windows-local test-portability issues (Linux CI unaffected). `uv sync --locked`, docs-drift, version-lockstep, changelog-parse all green.
- Reviewed by owner-judge; all findings addressed (blast-radius wording, alembic floor, behavioral tests, stale comment).

Found while testing; an installed-build gap the judge surfaced is worth a separate decision: installers don't ship `alembic.ini` at all, so packaged apps never run the migration chain (they rely on additive reconcile — `0008`'s index and `0006`/`0007`'s data repairs never apply). Shipping the ini would fix that but would also let `MigrationError` stop startup for installed users — owner's call, happy to follow up either way.

The PR restores default-engine generation by resolving the exported `OmniVoice` class and updates related documentation and notebook examples. It makes Alembic migrations independent of the working directory and supports platform-safe paths, with Alembic `>=1.16` and regression tests. Packaged installers still omit `alembic.ini`, so migration behavior in installers requires follow-up.

### CODE REVIEW

File: pyproject.toml [hunk 1]
```diff
@@ -86,7 +86,10 @@ dependencies = [
     "parakeet-mlx>=0.5.2 ; sys_platform == 'darwin' and platform_machine == 'arm64'",
     "demucs>=4.0.1",
     "yt-dlp>=2024.12.13",
-    "alembic>=1.13",
+    # >=1.15: alembic.ini relies on path_separator=os, which older alembic
+    # silently ignores and then colon-splits C:\ paths / space-splits POSIX
+    # paths containing spaces.
+    "alembic>=1.15",
```
[the remark this answers is not in the document]
Comment (debpalash) [reply pyproject.toml]: Fixed in d910b668 — floor raised to `alembic>=1.16`, lockfile regenerated (pinned 1.18.4 unchanged), migration-safety suite green.
