### ISSUE TITLE
[Bug] Transcribe stream dropped before emitting any segments

### ISSUE THREAD

**Issue by camilocarrai1997** [debpalash/VoiceStudio#255]
## Describe the bug

The transcription is still failing

## To reproduce

I just followed these steps to fix the pkg_resources error:
https://github.com/debpalash/OmniVoice-Studio/pull/253

The problem is that now I get the following error when the transcription is progressing:
Upload failed: Transcribe stream dropped before emitting any segments. Likely ASR backend failed to load — check backend log + Settings → Models.

Im using Whisper large-v3 (faster-whisper — default, cross-platform)

## Expected behavior

Transcribe video

## Screenshots / Logs

<img width="753" height="143" alt="Image" src="https://github.com/user-attachments/assets/febb7b0c-b162-4e31-b582-64d6440baad3" />

<img width="1901" height="65" alt="Image" src="https://github.com/user-attachments/assets/4f8cedc9-220e-4ec8-9827-64bb74e33d11" />

## Environment

- **OS:** Windows 11
- **Install method:** Desktop app
- **Version:** 0.3.0
- **GPU:** NVIDIA RTX 4070 ti Super
- **RAM:** 32GB

## Additional context

This error also keeps appearing:

Upload failed: No ASR backend is ready. Install WhisperX/faster-whisper/MLX Whisper or set OMNIVOICE_PRELOAD_TTS_ASR=1 before launching to use the PyTorch fallback.
 
This error appears when i use PyTorch Whisper (CUDA / CPU via transformers pipeline)

**Comment by debpalash** [comment]
Thanks for the detailed report, and for confirming you'd already applied #253.

The message you saw — *"Transcribe stream dropped before emitting any segments…"* — is unfortunately a **generic fallback** the UI shows whenever the transcribe stream closes without sending a specific error. It was hiding the real cause. I've pushed a fix (#259) that makes the backend always emit the **actual** failure (sanitized) instead of dropping the stream, so the next run will tell us exactly what's wrong.

On Windows + NVIDIA, the most common root cause is **faster-whisper / CTranslate2 not finding cuDNN 8**. PyTorch 2.8 ships cuDNN 9, but CTranslate2 needs cuDNN 8, so the app side-loads a cuDNN-8 copy from `.venv/Lib/site-packages/cudnn8_compat/`. If that folder is missing (some upgrade/repair paths don't run the cuDNN-8 install step), the model fails to load natively.

Could you help confirm, once you're on a build that includes #259:
1. Re-run the transcription and paste the **new** error text (it should now name the real failure).
2. The tail of the backend log around the failure — Settings → Logs, or `omnivoice_data/logs/backend.log`.
3. Whether this folder exists: `.venv\Lib\site-packages\cudnn8_compat\nvidia\cudnn\bin` (should contain `cudnn*64_8.dll`).

As a workaround in the meantime, switching the ASR backend in **Settings → Models** to **WhisperX** or **PyTorch Whisper (transformers)** avoids the CTranslate2/cuDNN path — though for the PyTorch fallback you'll currently need to launch with `OMNIVOICE_PRELOAD_TTS_ASR=1` (that requirement is on my list to smooth out).

**Comment by debpalash** [comment]
Reopening — this was auto-closed by a keyword in the PR description, not intentionally. The diagnostics improvement (#259) has shipped in **v0.3.1**, but the underlying Windows/CUDA root cause is **not yet confirmed**. Once you're on v0.3.1, please re-run transcription and share the now-surfaced error + backend log (and whether `.venv\Lib\site-packages\cudnn8_compat\nvidia\cudnn\bin` exists) so I can land the real fix. Keeping this open until then.

**Comment by camilocarrai1997** [comment]
Hello, the error message remains the same

I don't have the cudnn8_compat folder, so I assume that's the problem. The cudnn_ops_infer64_8.dll file is missing.

This is the backend log:

2026-06-03 03:32:14,624 INFO [omnivoice.dub_pipeline] Cache hit for job qmd3cjxe (hash 9d119590e161) → reusing artifacts from jnw0fpzl
2026-06-03 03:32:14,798 INFO [omnivoice.asr] whisperx loading ASR large-v3 on cuda (float16)
2026-06-03 03:32:18,088 INFO [speechbrain.utils.quirks] Applied quirks (see `speechbrain.utils.quirks`): [disable_jit_profiling, allow_tf32]
2026-06-03 03:32:18,089 INFO [speechbrain.utils.quirks] Excluded quirks specified by the `SB_DISABLE_QUIRKS` environment (comma-separated list): []
2026-06-03 03:32:22,428 INFO [pytorch_lightning.utilities.migration.utils] Lightning automatically upgraded your loaded checkpoint from v1.5.4 to v2.6.1. To apply the upgrade to your files permanently, run `python -m pytorch_lightning.utilities.upgrade_checkpoint C:\Users\username\AppData\Local\com.debpalash.omnivoice-studio\project\.venv\Lib\site-packages\whisperx\assets\pytorch_model.bin`
2026-06-03 03:32:22,460 INFO [omnivoice.asr] whisperx transcribing C:\Users\username\AppData\Local\Temp\tmpc9a7uloj.wav (word_timestamps=True)
Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!

**Comment by debpalash** [comment]
Perfect — that log pins it exactly:

> Could not locate cudnn_ops_infer64_8.dll. Please make sure it is in your library path!

That's the root cause. WhisperX and faster-whisper run on **CTranslate2**, which needs **cuDNN 8** — but PyTorch 2.8 ships cuDNN **9**. OmniVoice is supposed to side-load a cuDNN-8 copy from `.venv\Lib\site-packages\cudnn8_compat\`, and yours is missing it (hence the DLL can't be found). So this isn't a transcription bug per se — it's a missing native dependency in your install.

I'm working on two things:
1. Making the **PyTorch-Whisper** ASR backend usable as a drop-in fallback **without** needing `OMNIVOICE_PRELOAD_TTS_ASR=1` — it uses PyTorch's own (cuDNN 9) stack, so it sidesteps the CTranslate2/cuDNN-8 requirement entirely.
2. Making the cuDNN-8 (`cudnn8_compat`) install more robust so this folder is present after install/upgrade.

To help me target #2: did you install via the **desktop installer (.msi)** or from **source / `uv sync`**? And is this an upgrade from an older version, or a fresh install?

I'll follow up here when the fix lands in a build you can pull.

**Comment by camilocarrai1997** [comment]
Yes, it's via .msi and I updated from a previous version, 0.3.0. I'm currently on 0.3.3.

**Comment by debpalash** [comment]
**v0.3.4 is out** with the fallback fix. To get transcription working now:

1. Update to v0.3.4 (desktop: it'll auto-update, or grab the installer from Releases; Docker: `docker pull ghcr.io/debpalash/omnivoice-studio:latest`).
2. **Settings → Models → set the ASR backend to "PyTorch Whisper"** and retry the transcription.

That backend runs on PyTorch's own CUDA/cuDNN-9 stack, so it sidesteps the missing `cudnn_ops_infer64_8.dll` (cuDNN 8) entirely — and it no longer needs the `OMNIVOICE_PRELOAD_TTS_ASR=1` workaround; it loads its Whisper pipeline on demand. First run will download a Whisper model (~1.5 GB), then it should transcribe on your RTX 4070.

If you'd rather keep using faster-whisper/WhisperX (slightly faster), the underlying fix is to restore the bundled cuDNN-8 libs — I'm tracking that as a follow-up. Could you let me know (a) whether PyTorch Whisper works for you on v0.3.4, and (b) your install method (desktop .msi vs source)? I'll keep this open until you confirm.

**Comment by debpalash** [comment]
(Reopening — it got auto-closed by a keyword in a merge message, not on purpose. Keeping it open until you confirm.)

Thanks, that's the key detail: **.msi installer, upgraded from 0.3.0**. That confirms the root cause for the whole Windows desktop path — the installer's bootstrap runs `uv sync` but does **not** run the step that installs the side-by-side cuDNN 8 into `cudnn8_compat\`, so faster-whisper/WhisperX can't find `cudnn_ops_infer64_8.dll`. It's not specific to your machine.

For now, **v0.3.4 + Settings → Models → "PyTorch Whisper"** is the reliable path (it doesn't touch cuDNN 8). Please give that a try and let me know if transcription completes.

Separately I'm scoping the proper default-experience fix so faster-whisper works out of the box on Windows (either auto-installing the cuDNN-8 libs during setup, or auto-falling-back to PyTorch Whisper when the cuDNN-8 DLL is absent). That part needs a Windows test pass before it ships, so it'll come a bit later — but you're unblocked via PyTorch Whisper in the meantime.

**Comment by camilocarrai1997** [comment]
Hi, I managed to transcribe using PyTorch Whisper (the only problem is that it uses too much VRAM and takes a while to transcribe).

Despite being able to transcribe and dub, I'm getting the following error in the log:

2026-06-03 05:53:57,010 ERROR [omnivoice.model] Failed to load Pyannote pipeline (class=LOAD_FAILED): 'NoneType' object has no attribute 'to'

2026-06-03 05:53:57,015 WARNING [omnivoice.api] diarization fallback: Speaker diarization model failed to load even though an HF token was found (source=app, user=camilo12345). Most common causes: the pyannote/speaker-diarization-3.1 license has not been accepted on HuggingFace, or there is a pyannote/torch version mismatch. See backend logs for the underlying error. Falling back to a silence-gap heuristic; rapid speaker turns may be merged.

**Comment by debpalash** [comment]
Great — that confirms the transcription fix works in v0.3.4. Resolving this one (the original "transcribe stream dropped" bug). Three quick notes:

1. **Speed / VRAM:** PyTorch Whisper is the heavier path — it loads the full Whisper model into VRAM and batches less efficiently than faster-whisper. The faster path is faster-whisper/WhisperX, which needs the cuDNN-8 libs your .msi install was missing. I'm tracking the proper default-experience fix (auto-install `cudnn8_compat` during setup so faster-whisper works out of the box) — that'll restore the speed without you switching backends. If VRAM is tight, you can point PyTorch Whisper at a smaller model via `OMNIVOICE_PYTORCH_ASR_MODEL=openai/whisper-large-v3-turbo` (default) or `...whisper-medium`.

2. **Diarization error (separate from this issue):** `Failed to load Pyannote pipeline ... 'NoneType' object has no attribute 'to'` means the **pyannote/speaker-diarization-3.1 license hasn't been accepted** on HuggingFace (a valid token alone isn't enough for that gated model). Accept it here while logged in: https://huggingface.co/pyannote/speaker-diarization-3.1 — steps in [docs/features/diarization.md](https://github.com/debpalash/OmniVoice-Studio/blob/main/docs/features/diarization.md#license-acceptance-flow). Until then OmniVoice falls back to a silence-gap heuristic (which is why dubbing still completed, just with rougher speaker turns).

3. If diarization still fails **after** accepting that license, please open a new issue with the backend log and I'll dig in.

Thanks for the great back-and-forth debugging this — it pinned both the cuDNN-8 gap and validated the fallback.
